export const users = [
  {
    "id": 1,
    "first_name": "Akshay",
    "last_name": "Kumar",
    "email": "akshay.kumar@example.com",
    "gender": "Male",
  },
  {
    "id": 2,
    "first_name": "Rohit",
    "last_name": "Sharma",
    "email": "rohit.sharma@example.com",
    "gender": "Male",
  },
  {
    "id": 3,
    "first_name": "Priya",
    "last_name": "Verma",
    "email": "priya.verma@example.com",
    "gender": "Female",
  },
  {
    "id": 4,
    "first_name": "Amit",
    "last_name": "Singh",
    "email": "amit.singh@example.com",
    "gender": "Male",
  },
  {
    "id": 5,
    "first_name": "Neha",
    "last_name": "Gupta",
    "email": "neha.gupta@example.com",
    "gender": "Female",
  },
  {
    "id": 6,
    "first_name": "Rahul",
    "last_name": "Mehta",
    "email": "rahul.mehta@example.com",
    "gender": "Male",
  },
  {
    "id": 7,
    "first_name": "Pooja",
    "last_name": "Yadav",
    "email": "pooja.yadav@example.com",
    "gender": "Female",
  },
  {
    "id": 8,
    "first_name": "Vikas",
    "last_name": "Malhotra",
    "email": "vikas.malhotra@example.com",
    "gender": "Male",
  },
  {
    "id": 9,
    "first_name": "Anjali",
    "last_name": "Chauhan",
    "email": "anjali.chauhan@example.com",
    "gender": "Female",
  },
  {
    "id": 10,
    "first_name": "Sandeep",
    "last_name": "Patel",
    "email": "sandeep.patel@example.com",
    "gender": "Male",
  },

  {
    "id": 11,
    "first_name": "Kiran",
    "last_name": "Reddy",
    "email": "kiran.reddy@example.com",
    "gender": "Male",
  },
  {
    "id": 12,
    "first_name": "Sneha",
    "last_name": "Iyer",
    "email": "sneha.iyer@example.com",
    "gender": "Female",
  },
  {
    "id": 13,
    "first_name": "Arjun",
    "last_name": "Nair",
    "email": "arjun.nair@example.com",
    "gender": "Male",
  },
  {
    "id": 14,
    "first_name": "Ritika",
    "last_name": "Bansal",
    "email": "ritika.bansal@example.com",
    "gender": "Female",
  },
  {
    "id": 15,
    "first_name": "Manish",
    "last_name": "Joshi",
    "email": "manish.joshi@example.com",
    "gender": "Male",
  },
  {
    "id": 16,
    "first_name": "Kavya",
    "last_name": "Agarwal",
    "email": "kavya.agarwal@example.com",
    "gender": "Female",
  },
  {
    "id": 17,
    "first_name": "Deepak",
    "last_name": "Thakur",
    "email": "deepak.thakur@example.com",
    "gender": "Male",
  },
  {
    "id": 18,
    "first_name": "Nisha",
    "last_name": "Kapoor",
    "email": "nisha.kapoor@example.com",
    "gender": "Female",
  },
  {
    "id": 19,
    "first_name": "Mohit",
    "last_name": "Saxena",
    "email": "mohit.saxena@example.com",
    "gender": "Male",
  },
  {
    "id": 20,
    "first_name": "Ayesha",
    "last_name": "Khan",
    "email": "ayesha.khan@example.com",
    "gender": "Female",
  },

  {
    "id": 21,
    "first_name": "Ravi",
    "last_name": "Shukla",
    "email": "ravi.shukla@example.com",
    "gender": "Male",
  },
  {
    "id": 22,
    "first_name": "Swati",
    "last_name": "Mishra",
    "email": "swati.mishra@example.com",
    "gender": "Female",
  },
  {
    "id": 23,
    "first_name": "Nitin",
    "last_name": "Arora",
    "email": "nitin.arora@example.com",
    "gender": "Male",
  },
  {
    "id": 24,
    "first_name": "Pallavi",
    "last_name": "Goyal",
    "email": "pallavi.goyal@example.com",
    "gender": "Female",
  },
  {
    "id": 25,
    "first_name": "Saurabh",
    "last_name": "Jain",
    "email": "saurabh.jain@example.com",
    "gender": "Male",
  },
  {
    "id": 26,
    "first_name": "Isha",
    "last_name": "Pandey",
    "email": "isha.pandey@example.com",
    "gender": "Female",
  },
  {
    "id": 27,
    "first_name": "Harsh",
    "last_name": "Tiwari",
    "email": "harsh.tiwari@example.com",
    "gender": "Male",
  },
  {
    "id": 28,
    "first_name": "Megha",
    "last_name": "Rana",
    "email": "megha.rana@example.com",
    "gender": "Female",
  },
  {
    "id": 29,
    "first_name": "Alok",
    "last_name": "Tripathi",
    "email": "alok.tripathi@example.com",
    "gender": "Male",
  },
  {
    "id": 30,
    "first_name": "Simran",
    "last_name": "Kaur",
    "email": "simran.kaur@example.com",
    "gender": "Female",
  },

  {
    "id": 31,
    "first_name": "Aakash",
    "last_name": "Mittal",
    "email": "aakash.mittal@example.com",
    "gender": "Male",
  },
  {
    "id": 32,
    "first_name": "Renu",
    "last_name": "Sinha",
    "email": "renu.sinha@example.com",
    "gender": "Female",
  },
  {
    "id": 33,
    "first_name": "Vivek",
    "last_name": "Dubey",
    "email": "vivek.dubey@example.com",
    "gender": "Male",
  },
  {
    "id": 34,
    "first_name": "Payal",
    "last_name": "Jaiswal",
    "email": "payal.jaiswal@example.com",
    "gender": "Female",
  },
  {
    "id": 35,
    "first_name": "Ankit",
    "last_name": "Rawat",
    "email": "ankit.rawat@example.com",
    "gender": "Male",
  },
  {
    "id": 36,
    "first_name": "Bhavna",
    "last_name": "Negi",
    "email": "bhavna.negi@example.com",
    "gender": "Female",
  },
  {
    "id": 37,
    "first_name": "Gaurav",
    "last_name": "Bhardwaj",
    "email": "gaurav.bhardwaj@example.com",
    "gender": "Male",
  },
  {
    "id": 38,
    "first_name": "Tanvi",
    "last_name": "Kulkarni",
    "email": "tanvi.kulkarni@example.com",
    "gender": "Female",
  },
  {
    "id": 39,
    "first_name": "Prakash",
    "last_name": "Deshmukh",
    "email": "prakash.deshmukh@example.com",
    "gender": "Male",
  },
  {
    "id": 40,
    "first_name": "Sonali",
    "last_name": "More",
    "email": "sonali.more@example.com",
    "gender": "Female",
  },

  {
    "id": 41,
    "first_name": "Sunil",
    "last_name": "Pawar",
    "email": "sunil.pawar@example.com",
    "gender": "Male",
  },
  {
    "id": 42,
    "first_name": "Madhuri",
    "last_name": "Patil",
    "email": "madhuri.patil@example.com",
    "gender": "Female",
  },
  {
    "id": 43,
    "first_name": "Kunal",
    "last_name": "Bhat",
    "email": "kunal.bhat@example.com",
    "gender": "Male",
  },
  {
    "id": 44,
    "first_name": "Shruti",
    "last_name": "Shetty",
    "email": "shruti.shetty@example.com",
    "gender": "Female",
  },
  {
    "id": 45,
    "first_name": "Sameer",
    "last_name": "Kulkarni",
    "email": "sameer.kulkarni@example.com",
    "gender": "Male",
  },
  {
    "id": 46,
    "first_name": "Rashmi",
    "last_name": "Naik",
    "email": "rashmi.naik@example.com",
    "gender": "Female",
  },
  {
    "id": 47,
    "first_name": "Naveen",
    "last_name": "Hegde",
    "email": "naveen.hegde@example.com",
    "gender": "Male",
  },
  {
    "id": 48,
    "first_name": "Divya",
    "last_name": "Menon",
    "email": "divya.menon@example.com",
    "gender": "Female",
  }
];
